export const GET_ALL_BLOOD_FAILURE = "GET_ALL_BLOOD_FAILURE"
export const GET_ALL_BLOOD_REQUEST = "GET_ALL_BLOOD_REQUEST"
export const GET_ALL_BLOOD_SUCCESS = "GET_ALL_BLOOD_SUCCESS"


export const GET_ALL_QUESTIONS_FAILURE = "GET_ALL_QUESTIONS_FAILURE"
export const GET_ALL_QUESTIONS_REQUEST = "GET_ALL_QUESTIONS_REQUEST"
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS"


